language: python
sudo: false
python:
  - "2.7"
addons:
  apt:
    packages:
    - libev-dev
    - libsnappy-dev
env:
  - TOXENV=py27 BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin
  - TOXENV=py34 BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin
  - TOXENV=pypy BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin

install:
    - pip install codecov kazoo tox testinstances

before_script:
    - "python -m pykafka.test.kafka_instance 3 --download-dir /home/travis/kafka-bin &"
    - "sleep 10"

script:
    - tox

after_success:
    - codecov
